# Generated by Django 4.1.1 on 2022-09-15 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
        ('users', '0003_post_newuser_post'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Post',
        ),
        migrations.AlterField(
            model_name='newuser',
            name='post',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
