# Generated by Django 4.1.1 on 2022-09-15 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_delete_post_alter_newuser_post'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='post',
        ),
    ]
