# Generated by Django 4.1.1 on 2022-09-15 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_remove_post_user'),
        ('users', '0005_remove_newuser_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='post',
            field=models.ManyToManyField(to='post.post'),
        ),
    ]
