# Generated by Django 4.1.1 on 2022-09-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
        ('post', '0006_post_post_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(to='comments.comment'),
        ),
    ]
