# Generated by Django 4.1.1 on 2022-09-19 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_alter_post_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
