# Generated by Django 4.1.1 on 2022-09-17 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments_reply', '0001_initial'),
        ('comments', '0002_rename_comment_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='replys',
            field=models.ManyToManyField(to='comments_reply.commentreply'),
        ),
    ]
