# Generated by Django 4.1.1 on 2022-09-17 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_comments_replys'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='replys',
            new_name='replyies',
        ),
    ]
