# Generated by Django 4.1.1 on 2022-09-17 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0004_rename_replys_comments_replyies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='replyies',
            new_name='replies',
        ),
    ]
