# Generated by Django 4.1.1 on 2022-09-20 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post_image', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimages',
            name='file',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
