# Generated by Django 4.1.1 on 2022-09-17 21:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('comments_reply', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_owner', to=settings.AUTH_USER_MODEL),
        ),
    ]
