# Generated by Django 4.1.1 on 2022-09-19 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comments_reply', '0002_alter_commentreply_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentreply',
            options={'ordering': ['-date']},
        ),
    ]
